spring:
  datasource:
    url: jdbc:mysql://119.45.39.221:3306/xuan?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: t6QO9Z7M
    driver-class-name: com.mysql.cj.jdbc.Driver
